# Generated by Django 4.2 on 2023-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_tax_options_alter_tax_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax percentage(%)'),
        ),
    ]
