# Generated by Django 4.2 on 2023-05-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_openinghour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('vendor', 'day')},
        ),
    ]
