# Generated by Django 4.2 on 2023-07-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_alter_openinghour_from_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
