# Generated by Django 4.2 on 2023-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_data_order_vendor_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
